import { Mic, RotateCcw, Wand2 } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import { useTranslation } from "react-i18next"
import { toast } from "sonner"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { LoadingOverlay } from "@/components/common/LoadingOverlay"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { GenerateDialog, type GenerateDialogParams } from "@/features/learn/shared/GenerateDialog"
import { useFocusItem } from "@/features/learn/shared/useFocusItem"
import { PronunciationResultPanel } from "@/features/learn/speaking/PronunciationResultPanel"
import { SpeakingAttemptDetailDialog } from "@/features/learn/speaking/SpeakingAttemptDetailDialog"
import {
  useGenerateSpeakingPractice,
  useGenerateSpeakingPracticeFromAttempt,
  useGenerateSpeakingPracticeFromSection,
  useSpeakingMergedHistory,
  useSubmitSpeakingAttempt,
} from "@/features/learn/speaking/hooks"
import { TopicLibraryPanel } from "@/features/learn/speaking/library/TopicLibraryPanel"
import { SpeakingRecorder } from "@/features/learn/speaking/SpeakingRecorder"
import { ApiError } from "@/lib/http"
import { useAuthStore } from "@/stores/auth-store"
import type { SpeakingAttemptResult, SpeakingPracticeItem } from "@/types/api"

type PracticeView = "idle" | "runner" | "result"

export function SpeakingLearnPage() {
  const { t } = useTranslation()
  const userId = useAuthStore((state) => state.user?.userId ?? "")
  const { focusLabel } = useFocusItem()
  const autoGeneratedRef = useRef(false)

  const generate = useGenerateSpeakingPractice(userId)
  const submit = useSubmitSpeakingAttempt(userId)
  const generateFromAttempt = useGenerateSpeakingPracticeFromAttempt(userId)
  const generateFromSection = useGenerateSpeakingPracticeFromSection(userId)

  const [tab, setTab] = useState("practice")
  const [view, setView] = useState<PracticeView>("idle")
  const [currentItem, setCurrentItem] = useState<SpeakingPracticeItem | null>(null)
  const [recordedAudio, setRecordedAudio] = useState<Blob | null>(null)
  const [result, setResult] = useState<SpeakingAttemptResult | null>(null)
  const [detailAttemptId, setDetailAttemptId] = useState<number | null>(null)
  // "Làm lại" deep-link target for the library tab - set right before switching to "library" so
  // TopicLibraryPanel can auto-start that exact topic's Section on mount, then cleared once
  // consumed (see onInitialTopicHandled) so revisiting the tab later doesn't re-trigger it.
  const [libraryDeepLinkTopicId, setLibraryDeepLinkTopicId] = useState<number | null>(null)

  const { data: history, isLoading: historyLoading, isError: historyError } =
    useSpeakingMergedHistory(userId)

  // "Luyện tập với AI" from a merged-history row - dispatches to the learn or library
  // generate-from-mistakes endpoint depending on the row's source, then switches to the
  // "practice" tab (this domain has no separate "AI" tab the way dictation does).
  function handlePracticeWithAi(entry: { source: "LEARN" | "LIBRARY"; attemptOrSessionId: number }) {
    const mutation = entry.source === "LIBRARY" ? generateFromSection : generateFromAttempt
    mutation.mutate(entry.attemptOrSessionId, {
      onSuccess: () => setTab("practice"),
      onError: (error) =>
        toast.error(error instanceof ApiError ? error.message : t("learn.history.generateError")),
    })
  }

  function handleGenerate(focusItems?: string[]) {
    return (params: GenerateDialogParams) => {
      generate.mutate(
        { ...params, focusItems },
        {
          onSuccess: (item) => {
            setCurrentItem(item)
            setResult(null)
            setRecordedAudio(null)
            setView("runner")
          },
          onError: (error) =>
            toast.error(error instanceof ApiError ? error.message : t("learn.generateDialog.error")),
        }
      )
    }
  }

  // A "Luyện ngay" deep-link from a recommendation card auto-generates a sentence targeted at
  // that specific weak word, once, without requiring the learner to open the dialog themselves.
  useEffect(() => {
    if (autoGeneratedRef.current || !userId || !focusLabel) return
    autoGeneratedRef.current = true
    handleGenerate([focusLabel])({})
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, focusLabel])

  function handleSubmit() {
    if (!currentItem || !recordedAudio) return
    submit.mutate(
      { practiceItemId: currentItem.practiceItemId, audio: recordedAudio },
      {
        onSuccess: (data) => {
          setResult(data)
          setView("result")
        },
        onError: (error) =>
          toast.error(error instanceof ApiError ? error.message : t("learn.result.submitError")),
      }
    )
  }

  function handleRetry() {
    setView("idle")
    setCurrentItem(null)
    setRecordedAudio(null)
    setResult(null)
  }

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">{t("learn.speaking.title")}</h1>
        <p className="text-sm text-muted-foreground">{t("learn.speaking.subtitle")}</p>
      </div>

      <Tabs value={tab} onValueChange={(next) => typeof next === "string" && setTab(next)}>
        <TabsList className="h-auto gap-1 rounded-full border border-border/60 bg-muted/50 p-1.5 backdrop-blur-xl">
          <TabsTrigger value="practice">{t("learn.tabs.practice")}</TabsTrigger>
          <TabsTrigger value="history">{t("learn.tabs.history")}</TabsTrigger>
          <TabsTrigger value="library">{t("learn.tabs.library")}</TabsTrigger>
        </TabsList>

        <TabsContent value="practice" className="mt-6">
          {view === "idle" && (
            <Card>
              <CardContent className="py-10">
                <EmptyState
                  icon={<Mic className="size-6" />}
                  title={t("learn.speaking.emptyTitle")}
                  description={t("learn.speaking.emptyDescription")}
                  action={
                    <GenerateDialog
                      trigger={
                        <Button size="lg">
                          <Wand2 /> {t("learn.generateDialog.trigger")}
                        </Button>
                      }
                      onGenerate={handleGenerate()}
                      isGenerating={generate.isPending}
                    />
                  }
                />
              </CardContent>
            </Card>
          )}

          {view === "runner" && currentItem && (
            <div className="relative flex flex-col gap-4">
              <LoadingOverlay show={submit.isPending} label={t("common.grading")} />
              <div className="flex flex-wrap items-center gap-2">
                {currentItem.topic && <Badge variant="secondary">{currentItem.topic}</Badge>}
                {currentItem.level && <Badge variant="outline">{currentItem.level}</Badge>}
                {currentItem.examType && <Badge variant="outline">{currentItem.examType}</Badge>}
              </div>

              <Card>
                <CardContent className="flex flex-col gap-2 py-6">
                  {/* Task requirement in the app language - speaking has no per-question prompt, so
                      the "read aloud and record" instruction is stated here above the target text. */}
                  <p className="text-sm font-medium text-primary">{t("learn.speaking.instruction")}</p>
                  <p className="text-lg font-medium">{currentItem.targetText}</p>
                  {currentItem.translation && (
                    <p className="text-sm text-muted-foreground">{currentItem.translation}</p>
                  )}
                  {currentItem.sampleAudioUrl && (
                    <div className="mt-2 flex flex-col gap-1">
                      <p className="text-xs font-medium text-muted-foreground">{t("learn.speaking.sampleAudio")}</p>
                      {/* eslint-disable-next-line jsx-a11y/media-has-caption -- reference model audio, no captions source exists */}
                      <audio controls className="w-full" src={currentItem.sampleAudioUrl} />
                    </div>
                  )}
                </CardContent>
              </Card>

              <SpeakingRecorder onRecorded={setRecordedAudio} disabled={submit.isPending} />

              <Button
                size="lg"
                className="h-12 w-full"
                onClick={handleSubmit}
                disabled={!recordedAudio}
                loading={submit.isPending}
              >
                {t("learn.speaking.submit")}
              </Button>
            </div>
          )}

          {view === "result" && result && (
            <PronunciationResultPanel
              overall={result.overall}
              words={result.words}
              transcript={result.transcript}
              weakPhonemes={result.weakPhonemes}
              actionAdvice={result.actionAdvice}
              onRetry={handleRetry}
            />
          )}
        </TabsContent>

        <TabsContent value="history" className="mt-6">
          {historyLoading && (
            <div className="flex flex-col gap-2">
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
            </div>
          )}
          {historyError && <ErrorState />}
          {!historyLoading && !historyError && (!history || history.length === 0) && (
            <EmptyState icon={<Mic className="size-6" />} title={t("learn.speaking.noHistory")} />
          )}
          {!historyLoading && history && history.length > 0 && (
            <div className="flex flex-col gap-2">
              {history.map((entry) => {
                const key = `${entry.source}-${entry.attemptOrSessionId}`
                const scorePercent = entry.score != null ? Math.round(entry.score * 100) : null
                const isGeneratingThis =
                  (entry.source === "LIBRARY" ? generateFromSection : generateFromAttempt).isPending &&
                  (entry.source === "LIBRARY" ? generateFromSection : generateFromAttempt).variables ===
                    entry.attemptOrSessionId
                return (
                  <div
                    key={key}
                    className="flex flex-col gap-3 rounded-2xl border border-border/60 bg-card px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
                  >
                    <button
                      type="button"
                      onClick={() =>
                        entry.source === "LEARN" && setDetailAttemptId(entry.attemptOrSessionId)
                      }
                      className="flex flex-1 items-center gap-3 text-left"
                    >
                      <Badge variant="secondary" className="shrink-0 text-[0.65rem]">
                        {entry.source === "LIBRARY" ? t("learn.tabs.library") : t("learn.tabs.practice")}
                      </Badge>
                      {scorePercent != null && (
                        <Badge variant={scorePercent >= 80 ? "default" : "secondary"}>
                          {scorePercent}%
                        </Badge>
                      )}
                    </button>

                    <div className="flex gap-2">
                      {/* Speaking's library Sections have no dedicated per-section route (same
                          limitation as listening), but the merged-history row now carries topicId
                          (resolved server-side from sectionId) - "Làm lại" passes it down to
                          TopicLibraryPanel via component state, which auto-starts that exact topic's
                          Section on mount instead of just landing on the topic grid. */}
                      {entry.source === "LIBRARY" && entry.topicId != null && (
                        <Button
                          variant="outline"
                          size="sm"
                          className="h-8 gap-1.5 text-xs"
                          onClick={() => {
                            setLibraryDeepLinkTopicId(entry.topicId)
                            setTab("library")
                          }}
                        >
                          <RotateCcw className="size-3.5" />
                          {t("learn.history.retryLibrary")}
                        </Button>
                      )}
                      <Button
                        variant="outline"
                        size="sm"
                        className="h-8 gap-1.5 text-xs"
                        disabled={isGeneratingThis}
                        onClick={() => handlePracticeWithAi(entry)}
                      >
                        <Wand2 className="size-3.5" />
                        {t("learn.history.retryAi")}
                      </Button>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </TabsContent>

        <TabsContent value="library" className="mt-6">
          <TopicLibraryPanel
            userId={userId}
            initialTopicId={libraryDeepLinkTopicId}
            onInitialTopicHandled={() => setLibraryDeepLinkTopicId(null)}
          />
        </TabsContent>
      </Tabs>

      <SpeakingAttemptDetailDialog
        userId={userId}
        attemptId={detailAttemptId}
        onOpenChange={(open) => !open && setDetailAttemptId(null)}
      />
    </div>
  )
}
