import { BookMarked, Wand2 } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import { useTranslation } from "react-i18next"
import { toast } from "sonner"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { GenerateDialog, type GenerateDialogParams } from "@/features/learn/shared/GenerateDialog"
import { useFocusItem } from "@/features/learn/shared/useFocusItem"
import { VocabAttemptDetailDialog } from "@/features/learn/vocabulary/VocabAttemptDetailDialog"
import {
  useGenerateVocabPractice,
  useVocabPracticeHistory,
  useSubmitVocabAttempt,
} from "@/features/learn/vocabulary/hooks"
import { SectionResultPanel } from "@/features/learn/vocabulary/library/SectionResultPanel"
import { SectionRunner } from "@/features/learn/vocabulary/library/SectionRunner"
import { TopicLibraryPanel } from "@/features/learn/vocabulary/library/TopicLibraryPanel"
import { useSubmitVocabSectionAnswer } from "@/features/learn/vocabulary/library/hooks"
import { VocabResultPanel } from "@/features/learn/vocabulary/VocabResultPanel"
import { VocabRunner } from "@/features/learn/vocabulary/VocabRunner"
import { ApiError } from "@/lib/http"
import { useAuthStore } from "@/stores/auth-store"
import type { SectionCard, SectionProgress, VocabAttemptResult, VocabPracticeItem } from "@/types/api"

type PracticeView = "idle" | "runner" | "result"
type LibraryView = "topics" | "running" | "done"

export function VocabularyLearnPage() {
  const { t } = useTranslation()
  const userId = useAuthStore((state) => state.user?.userId ?? "")
  const { focusLabel } = useFocusItem()
  const autoGeneratedRef = useRef(false)

  const generate = useGenerateVocabPractice(userId)
  const submit = useSubmitVocabAttempt(userId)

  const [view, setView] = useState<PracticeView>("idle")
  const [currentItem, setCurrentItem] = useState<VocabPracticeItem | null>(null)
  const [result, setResult] = useState<VocabAttemptResult | null>(null)
  const [detailAttemptId, setDetailAttemptId] = useState<number | null>(null)

  const [libraryView, setLibraryView] = useState<LibraryView>("topics")
  const [currentCard, setCurrentCard] = useState<SectionCard | null>(null)
  const [lastProgress, setLastProgress] = useState<SectionProgress | null>(null)
  const submitSectionAnswer = useSubmitVocabSectionAnswer(userId)

  const { data: history, isLoading: historyLoading, isError: historyError } =
    useVocabPracticeHistory(userId)

  function handleSectionStarted(card: SectionCard) {
    setCurrentCard(card)
    setLibraryView("running")
  }

  function handleSectionAnswerSubmit(answer?: string) {
    if (!currentCard) return
    submitSectionAnswer.mutate(
      { sectionId: currentCard.sectionId, request: { submittedAnswer: answer } },
      {
        onSuccess: (result) => {
          setLastProgress(result.progress)
          if (result.completed) {
            setCurrentCard(null)
            setLibraryView("done")
            return
          }
          if (currentCard.cardKind === "QUIZ") {
            toast[result.correct ? "success" : "error"](
              result.correct
                ? t("learn.vocabulary.library.correctToast")
                : t("learn.vocabulary.library.wrongToast", { answer: result.correctAnswer ?? "" })
            )
          }
          setCurrentCard(result.nextCard)
        },
        onError: (error) =>
          toast.error(error instanceof ApiError ? error.message : t("learn.vocabulary.library.answerError")),
      }
    )
  }

  function handleBackToTopics() {
    setLibraryView("topics")
    setCurrentCard(null)
    setLastProgress(null)
  }

  function handleGenerate(focusItems?: string[]) {
    return (params: GenerateDialogParams) => {
      generate.mutate(
        { ...params, focusItems },
        {
          onSuccess: (item) => {
            setCurrentItem(item)
            setResult(null)
            setView("runner")
          },
          onError: (error) =>
            toast.error(error instanceof ApiError ? error.message : t("learn.generateDialog.error")),
        }
      )
    }
  }

  // A "Luyện ngay" deep-link from a recommendation card auto-generates a set targeted at that
  // specific weak word, once, without requiring the learner to open the dialog themselves.
  useEffect(() => {
    if (autoGeneratedRef.current || !userId || !focusLabel) return
    autoGeneratedRef.current = true
    handleGenerate([focusLabel])({})
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, focusLabel])

  function handleSubmit(answers: string[]) {
    if (!currentItem) return
    submit.mutate(
      { practiceItemId: currentItem.practiceItemId, answers },
      {
        onSuccess: (data) => {
          setResult(data)
          setView("result")
        },
        onError: (error) =>
          toast.error(error instanceof ApiError ? error.message : t("learn.result.submitError")),
      }
    )
  }

  function handleRetry() {
    setView("idle")
    setCurrentItem(null)
    setResult(null)
  }

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">{t("learn.vocabulary.title")}</h1>
        <p className="text-sm text-muted-foreground">{t("learn.vocabulary.subtitle")}</p>
      </div>

      <Tabs defaultValue="practice">
        <TabsList className="h-auto gap-1 rounded-full border border-border/60 bg-muted/50 p-1.5 backdrop-blur-xl">
          <TabsTrigger value="practice">{t("learn.tabs.practice")}</TabsTrigger>
          <TabsTrigger value="history">{t("learn.tabs.history")}</TabsTrigger>
          <TabsTrigger value="library">{t("learn.tabs.library")}</TabsTrigger>
        </TabsList>

        <TabsContent value="practice" className="mt-6">
          {view === "idle" && (
            <Card>
              <CardContent className="py-10">
                <EmptyState
                  icon={<BookMarked className="size-6" />}
                  title={t("learn.vocabulary.emptyTitle")}
                  description={t("learn.vocabulary.emptyDescription")}
                  action={
                    <GenerateDialog
                      trigger={
                        <Button size="lg">
                          <Wand2 /> {t("learn.generateDialog.trigger")}
                        </Button>
                      }
                      onGenerate={handleGenerate()}
                      isGenerating={generate.isPending}
                    />
                  }
                />
              </CardContent>
            </Card>
          )}

          {view === "runner" && currentItem && (
            <div className="flex flex-col gap-4">
              <div className="flex flex-wrap items-center gap-2">
                {currentItem.topic && <Badge variant="secondary">{currentItem.topic}</Badge>}
                {currentItem.level && <Badge variant="outline">{currentItem.level}</Badge>}
                {currentItem.examType && <Badge variant="outline">{currentItem.examType}</Badge>}
              </div>
              <VocabRunner item={currentItem} onSubmit={handleSubmit} isSubmitting={submit.isPending} />
            </div>
          )}

          {view === "result" && result && (
            <VocabResultPanel
              accuracy={result.accuracy}
              results={result.results}
              actionAdvice={result.actionAdvice}
              onRetry={handleRetry}
            />
          )}
        </TabsContent>

        <TabsContent value="history" className="mt-6">
          {historyLoading && (
            <div className="flex flex-col gap-2">
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
            </div>
          )}
          {historyError && <ErrorState />}
          {!historyLoading && !historyError && (!history || history.length === 0) && (
            <EmptyState icon={<BookMarked className="size-6" />} title={t("learn.vocabulary.noHistory")} />
          )}
          {!historyLoading && history && history.length > 0 && (
            <div className="flex flex-col gap-2">
              {history.map((entry) => (
                <button
                  key={entry.attemptId}
                  type="button"
                  onClick={() => setDetailAttemptId(entry.attemptId)}
                  className="flex items-center justify-between rounded-2xl border border-border/60 bg-card px-4 py-3 text-left transition-colors hover:bg-muted/50"
                >
                  <div className="flex flex-col gap-0.5">
                    <span className="font-medium">{entry.topic ?? t("learn.vocabulary.title")}</span>
                    <span className="text-xs text-muted-foreground">
                      {[entry.level, entry.examType].filter(Boolean).join(" · ")}
                    </span>
                  </div>
                  <Badge variant={entry.score >= 0.8 ? "default" : "secondary"}>
                    {Math.round(entry.score * 100)}%
                  </Badge>
                </button>
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="library" className="mt-6">
          {libraryView === "topics" && (
            <TopicLibraryPanel userId={userId} onSectionStarted={handleSectionStarted} />
          )}
          {libraryView === "running" && currentCard && (
            <SectionRunner
              userId={userId}
              card={currentCard}
              isSubmitting={submitSectionAnswer.isPending}
              onSubmit={handleSectionAnswerSubmit}
            />
          )}
          {libraryView === "done" && (
            <SectionResultPanel
              totalWords={lastProgress?.totalWords ?? 0}
              onBackToTopics={handleBackToTopics}
            />
          )}
        </TabsContent>
      </Tabs>

      <VocabAttemptDetailDialog
        userId={userId}
        attemptId={detailAttemptId}
        onOpenChange={(open) => !open && setDetailAttemptId(null)}
      />
    </div>
  )
}
