import { RotateCcw, SpellCheck, Wand2 } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import { useTranslation } from "react-i18next"
import { useNavigate } from "react-router-dom"
import { toast } from "sonner"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { GenerateDialog, type GenerateDialogParams } from "@/features/learn/shared/GenerateDialog"
import { useFocusItem } from "@/features/learn/shared/useFocusItem"
import { GrammarAttemptDetailDialog } from "@/features/learn/grammar/GrammarAttemptDetailDialog"
import {
  useGenerateGrammarPractice,
  useGenerateGrammarPracticeFromAttempt,
  useGenerateGrammarPracticeFromSession,
  useGrammarMergedHistory,
  useSubmitGrammarAttempt,
} from "@/features/learn/grammar/hooks"
import { GrammarResultPanel } from "@/features/learn/grammar/GrammarResultPanel"
import { GrammarRunner } from "@/features/learn/grammar/GrammarRunner"
import { TopicLibraryPanel } from "@/features/learn/grammar/library/TopicLibraryPanel"
import { ApiError } from "@/lib/http"
import { useAuthStore } from "@/stores/auth-store"
import type { GrammarAttemptResult, GrammarPracticeItem } from "@/types/api"

type PracticeView = "idle" | "runner" | "result"

export function GrammarLearnPage() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const userId = useAuthStore((state) => state.user?.userId ?? "")
  const { focusLabel } = useFocusItem()
  const autoGeneratedRef = useRef(false)

  const generate = useGenerateGrammarPractice(userId)
  const submit = useSubmitGrammarAttempt(userId)
  const generateFromAttempt = useGenerateGrammarPracticeFromAttempt(userId)
  const generateFromSession = useGenerateGrammarPracticeFromSession(userId)

  const [tab, setTab] = useState("practice")
  const [view, setView] = useState<PracticeView>("idle")
  const [currentItem, setCurrentItem] = useState<GrammarPracticeItem | null>(null)
  const [result, setResult] = useState<GrammarAttemptResult | null>(null)
  const [detailAttemptId, setDetailAttemptId] = useState<number | null>(null)

  const { data: history, isLoading: historyLoading, isError: historyError } =
    useGrammarMergedHistory(userId)

  // "Luyện tập với AI" from a merged-history row - dispatches to the learn or library
  // generate-from-mistakes endpoint depending on the row's source, then switches to the
  // "practice" tab (this domain has no separate "AI" tab the way dictation does).
  function handlePracticeWithAi(entry: { source: "LEARN" | "LIBRARY"; attemptOrSessionId: number }) {
    const mutation = entry.source === "LIBRARY" ? generateFromSession : generateFromAttempt
    mutation.mutate(entry.attemptOrSessionId, {
      onSuccess: () => setTab("practice"),
      onError: (error) =>
        toast.error(error instanceof ApiError ? error.message : t("learn.history.generateError")),
    })
  }

  function handleGenerate(focusItems?: string[]) {
    return (params: GenerateDialogParams) => {
      generate.mutate(
        { ...params, focusItems },
        {
          onSuccess: (item) => {
            setCurrentItem(item)
            setResult(null)
            setView("runner")
          },
          onError: (error) =>
            toast.error(error instanceof ApiError ? error.message : t("learn.generateDialog.error")),
        }
      )
    }
  }

  // A "Luyện ngay" deep-link from a recommendation card auto-generates a set targeted at that
  // specific weak rule, once, without requiring the learner to open the dialog themselves.
  useEffect(() => {
    if (autoGeneratedRef.current || !userId || !focusLabel) return
    autoGeneratedRef.current = true
    handleGenerate([focusLabel])({})
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, focusLabel])

  function handleSubmit(answers: string[]) {
    if (!currentItem) return
    submit.mutate(
      { practiceItemId: currentItem.practiceItemId, answers },
      {
        onSuccess: (data) => {
          setResult(data)
          setView("result")
        },
        onError: (error) =>
          toast.error(error instanceof ApiError ? error.message : t("learn.result.submitError")),
      }
    )
  }

  function handleRetry() {
    setView("idle")
    setCurrentItem(null)
    setResult(null)
  }

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">{t("learn.grammar.title")}</h1>
        <p className="text-sm text-muted-foreground">{t("learn.grammar.subtitle")}</p>
      </div>

      <Tabs value={tab} onValueChange={(next) => typeof next === "string" && setTab(next)}>
        <TabsList className="h-auto gap-1 rounded-full border border-border/60 bg-muted/50 p-1.5 backdrop-blur-xl">
          <TabsTrigger value="practice">{t("learn.tabs.practice")}</TabsTrigger>
          <TabsTrigger value="history">{t("learn.tabs.history")}</TabsTrigger>
          <TabsTrigger value="library">{t("learn.tabs.library")}</TabsTrigger>
        </TabsList>

        <TabsContent value="practice" className="mt-6">
          {view === "idle" && (
            <Card>
              <CardContent className="py-10">
                <EmptyState
                  icon={<SpellCheck className="size-6" />}
                  title={t("learn.grammar.emptyTitle")}
                  description={t("learn.grammar.emptyDescription")}
                  action={
                    <GenerateDialog
                      trigger={
                        <Button size="lg">
                          <Wand2 /> {t("learn.generateDialog.trigger")}
                        </Button>
                      }
                      onGenerate={handleGenerate()}
                      isGenerating={generate.isPending}
                    />
                  }
                />
              </CardContent>
            </Card>
          )}

          {view === "runner" && currentItem && (
            <div className="flex flex-col gap-4">
              <div className="flex flex-wrap items-center gap-2">
                {currentItem.topic && <Badge variant="secondary">{currentItem.topic}</Badge>}
                {currentItem.level && <Badge variant="outline">{currentItem.level}</Badge>}
                {currentItem.examType && <Badge variant="outline">{currentItem.examType}</Badge>}
              </div>
              <GrammarRunner item={currentItem} onSubmit={handleSubmit} isSubmitting={submit.isPending} />
            </div>
          )}

          {view === "result" && result && (
            <GrammarResultPanel
              accuracy={result.accuracy}
              results={result.results}
              actionAdvice={result.actionAdvice}
              onRetry={handleRetry}
            />
          )}
        </TabsContent>

        <TabsContent value="history" className="mt-6">
          {historyLoading && (
            <div className="flex flex-col gap-2">
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
            </div>
          )}
          {historyError && <ErrorState />}
          {!historyLoading && !historyError && (!history || history.length === 0) && (
            <EmptyState icon={<SpellCheck className="size-6" />} title={t("learn.grammar.noHistory")} />
          )}
          {!historyLoading && history && history.length > 0 && (
            <div className="flex flex-col gap-2">
              {history.map((entry) => {
                const key = `${entry.source}-${entry.attemptOrSessionId}`
                const scorePercent = entry.score != null ? Math.round(entry.score * 100) : null
                const isGeneratingThis =
                  (entry.source === "LIBRARY" ? generateFromSession : generateFromAttempt).isPending &&
                  (entry.source === "LIBRARY" ? generateFromSession : generateFromAttempt).variables ===
                    entry.attemptOrSessionId
                return (
                  <div
                    key={key}
                    className="flex flex-col gap-3 rounded-2xl border border-border/60 bg-card px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
                  >
                    <button
                      type="button"
                      onClick={() =>
                        entry.source === "LEARN" && setDetailAttemptId(entry.attemptOrSessionId)
                      }
                      className="flex flex-1 items-center gap-3 text-left"
                    >
                      <Badge variant="secondary" className="shrink-0 text-[0.65rem]">
                        {entry.source === "LIBRARY" ? t("learn.tabs.library") : t("learn.tabs.practice")}
                      </Badge>
                      {scorePercent != null && (
                        <Badge variant={scorePercent >= 80 ? "default" : "secondary"}>
                          {scorePercent}%
                        </Badge>
                      )}
                    </button>

                    <div className="flex gap-2">
                      {entry.source === "LIBRARY" && entry.topicId != null && (
                        <Button
                          variant="outline"
                          size="sm"
                          className="h-8 gap-1.5 text-xs"
                          onClick={() => navigate(`/learn/grammar/library/topics/${entry.topicId}`)}
                        >
                          <RotateCcw className="size-3.5" />
                          {t("learn.history.retryLibrary")}
                        </Button>
                      )}
                      <Button
                        variant="outline"
                        size="sm"
                        className="h-8 gap-1.5 text-xs"
                        disabled={isGeneratingThis}
                        onClick={() => handlePracticeWithAi(entry)}
                      >
                        <Wand2 className="size-3.5" />
                        {t("learn.history.retryAi")}
                      </Button>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </TabsContent>

        <TabsContent value="library" className="mt-6">
          <TopicLibraryPanel userId={userId} />
        </TabsContent>
      </Tabs>

      <GrammarAttemptDetailDialog
        userId={userId}
        attemptId={detailAttemptId}
        onOpenChange={(open) => !open && setDetailAttemptId(null)}
      />
    </div>
  )
}
